#!/bin/sh

echo "Switching to branch master"
git checkout master

echo "Building app"
npm run build

echo "Deploying files to server"
rsync -avP build/ root@45.33.38.87:/var/www/alvinkgao.com/
echo "Deployment complete"
